apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-debit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.1"
  POD_NAME: "go-debit"
  PORT: "5002"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  NO_AZ: "true"
  #SERVER_URL_DOMAIN: "http://svc-go-account.test-a.svc.cluster.local:5000"
  SERVER_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID: "129t4y8eoj"
  
  #SERVER_URL_DOMAIN2: "http://svc-go-payfee.test-a.svc.cluster.local:5004"
  SERVER_URL_DOMAIN2: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID2: "5jdsds1yli"